# Generated by Django 5.2.16 on 2026-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="api_calls_count",
            field=models.CharField(default="5000+ API Calls", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="apis_count",
            field=models.CharField(default="40+ APIs", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="case_study_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="db_tables_count",
            field=models.CharField(default="25+ DB Tables", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="status_badge",
            field=models.CharField(default="Production Ready", max_length=50),
        ),
    ]
