# Generated by Django 5.2.16 on 2026-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=150)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("credential_url", models.URLField(blank=True, null=True)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/pdf/"
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificates/img/"
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Vyankateshwar Pund - Software Engineer Resume",
                        max_length=150,
                    ),
                ),
                ("file", models.FileField(upload_to="resume/")),
                ("is_active", models.BooleanField(default=True)),
                ("total_downloads", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
