# Generated by Django 5.2.16 on 2026-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("image", models.ImageField(upload_to="gallery/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Projects", "Projects & Code"),
                            ("Certificates", "Certificates & Credentials"),
                            ("Workspace", "Workspace & Tech Setup"),
                            ("Events", "Events & Hackathons"),
                        ],
                        default="Projects",
                        max_length=50,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
