# Generated by Django 5.2.16 on 2026-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Backend", "Backend Development"),
                            ("Frontend", "Frontend Development"),
                            ("Database", "Databases & ORM"),
                            ("Tools", "Developer Tools & Platforms"),
                            ("Concepts", "Software Concepts & Architecture"),
                            ("Soft Skills", "Soft Skills & Leadership"),
                        ],
                        default="Backend",
                        max_length=50,
                    ),
                ),
                (
                    "proficiency_percent",
                    models.IntegerField(
                        default=85, help_text="Value between 0 and 100"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="bi bi-code-slash",
                        help_text="Bootstrap or FontAwesome icon class",
                        max_length=100,
                    ),
                ),
                ("is_featured", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "-proficiency_percent"],
            },
        ),
    ]
