# Generated by Django 5.2.16 on 2026-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="level_label",
            field=models.CharField(default="Expert", max_length=50),
        ),
        migrations.AddField(
            model_name="skill",
            name="problems_solved",
            field=models.CharField(default="120+ Problems", max_length=50),
        ),
        migrations.AddField(
            model_name="skill",
            name="projects_count",
            field=models.CharField(default="15 Projects", max_length=50),
        ),
        migrations.AddField(
            model_name="skill",
            name="years_experience",
            field=models.CharField(default="2 Years", max_length=50),
        ),
    ]
