# Generated by Django 5.2.16 on 2026-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hackathon", "Hackathon"),
                            ("Award", "Award"),
                            ("Coding", "Coding Platform / Contest"),
                            ("Internship", "Internship"),
                            ("Training", "Training & Workshop"),
                        ],
                        default="Award",
                        max_length=50,
                    ),
                ),
                ("organization", models.CharField(max_length=150)),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                ("certificate_link", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=150)),
                ("field_of_study", models.CharField(max_length=150)),
                ("start_year", models.CharField(max_length=10)),
                ("end_year", models.CharField(max_length=10)),
                ("cgpa", models.CharField(default="8.06", max_length=20)),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-end_year"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=150)),
                ("location", models.CharField(default="India", max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "responsibilities",
                    models.TextField(help_text="Use bullet points or newlines"),
                ),
                (
                    "tech_stack_used",
                    models.CharField(
                        help_text="Comma separated technologies", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Experience",
                "verbose_name_plural": "Work Experiences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProfileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Vyankateshwar Santosh Pund", max_length=100
                    ),
                ),
                (
                    "title_roles",
                    models.CharField(
                        default="Junior Software Engineer | Python Developer | Django Backend Developer | Full Stack Developer",
                        max_length=255,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Amravati, Maharashtra, India", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="pundvyankateshwar@gmail.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(default="+91 8263986554", max_length=20)),
                (
                    "linkedin_url",
                    models.URLField(
                        default="https://linkedin.com/in/vyankateshwar-pund-7a654632b"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(default="https://github.com/vyankateshwarpund"),
                ),
                ("about_summary", models.TextField()),
                ("career_goals", models.TextField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("projects_completed_count", models.IntegerField(default=15)),
                (
                    "years_experience",
                    models.CharField(default="1+ Years", max_length=20),
                ),
                ("technologies_mastered", models.IntegerField(default=12)),
                ("github_contributions_count", models.IntegerField(default=450)),
            ],
            options={
                "verbose_name": "Profile Information",
                "verbose_name_plural": "Profile Information",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Bootstrap or FontAwesome icon class e.g. bi bi-code-slash",
                        max_length=100,
                    ),
                ),
                ("short_description", models.CharField(max_length=255)),
                ("full_description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("url", models.URLField()),
                (
                    "icon_class",
                    models.CharField(help_text="e.g., bi bi-github", max_length=50),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
