# Generated by Django 5.2.16 on 2026-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "icon_class",
                    models.CharField(default="bi bi-check-circle-fill", max_length=100),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "year"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=150)),
                ("content", models.TextField()),
                ("rating", models.IntegerField(default=5)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="profileinfo",
            name="technologies_mastered",
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="hours_coding_count",
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="internships_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="technologies_count",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="profileinfo",
            name="github_contributions_count",
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name="profileinfo",
            name="projects_completed_count",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="profileinfo",
            name="title_roles",
            field=models.CharField(
                default="Junior Software Engineer | Python Developer | Django Backend Developer | Python Full Stack Developer",
                max_length=255,
            ),
        ),
    ]
